/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package warehouse;

import backend.Import;
import javax.swing.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JTextField;

/**
 *
 * @author DotNet
 */
public class Import_GUI extends javax.swing.JInternalFrame {

    private Import importManager;
    private Connection con;
    /**
     * Creates new form Import
     */
    public Import_GUI() {
    initComponents(); // Initialize GUI components (assumed to set up PageIDField)

    // Establish database connection
    try {
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory management system", "root", "");
        System.out.println("Connection Successful");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database connection failed: " + e.getMessage(), 
                                      "Connection Error", JOptionPane.ERROR_MESSAGE);
        con = null;
    }

    // Initialize the database manager
    importManager = new Import();

    // Configure Current_DateField to display current date/time on focus
    Current_DateField.setEditable(false);
    Current_DateField.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent evt) {
            Current_DateField.setText(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
        }
    });

    // Configure PageIDField: non-editable and auto-incremented
    PageIDField.setEditable(false);
    PageIDField.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent evt) {
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection is not established.", 
                                              "Connection Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                // Use COALESCE to handle NULL case when table is empty
                String sql = "SELECT COALESCE(MAX(`Page ID`), 0) + 1 AS PageID FROM `accounting 71 a`";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    int nextId = rs.getInt("PageID");
                    PageIDField.setText(String.valueOf(nextId));
                } // No else needed; COALESCE ensures we get 1 for an empty table

                rs.close();
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error fetching next ID: " + e.getMessage(), 
                                              "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importPanel = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        Accounting_70Panel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        Accounting_71_APanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MinistryLabel = new javax.swing.JLabel();
        OfficeLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ProductNameField = new javax.swing.JTextField();
        QuantityField = new javax.swing.JTextField();
        UnitField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NoteArea = new javax.swing.JTextArea();
        Date_Of_OrderChooser = new com.toedter.calendar.JDateChooser();
        Date_Of_SaleChooser = new com.toedter.calendar.JDateChooser();
        RecipentField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        View_SearchButton = new javax.swing.JButton();
        update_deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        Current_DateField = new javax.swing.JTextField();
        PageIDField = new javax.swing.JTextField();

        importPanel.setBackground(new java.awt.Color(204, 255, 255));
        importPanel.setPreferredSize(new java.awt.Dimension(687, 610));
        importPanel.setLayout(new java.awt.BorderLayout());

        Accounting_70Panel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Product name");

        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Quantity");

        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Unit");

        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Price");

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Accounting_70PanelLayout = new javax.swing.GroupLayout(Accounting_70Panel);
        Accounting_70Panel.setLayout(Accounting_70PanelLayout);
        Accounting_70PanelLayout.setHorizontalGroup(
            Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounting_70PanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(Accounting_70PanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(55, 55, 55)
                        .addComponent(jTextField19))
                    .addGroup(Accounting_70PanelLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(84, 84, 84)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Accounting_70PanelLayout.createSequentialGroup()
                        .addGroup(Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField21)
                            .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))
                .addGap(0, 353, Short.MAX_VALUE))
        );
        Accounting_70PanelLayout.setVerticalGroup(
            Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounting_70PanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Accounting_70PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Accounting 70", Accounting_70Panel);

        Accounting_71_APanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Product");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantity");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Unit");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Price ");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Date");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Page ID");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Note");

        MinistryLabel.setForeground(new java.awt.Color(0, 0, 0));
        MinistryLabel.setText("Ministry\\ Reconstruction and implementation");

        OfficeLabel.setForeground(new java.awt.Color(0, 0, 0));
        OfficeLabel.setText("The Office\\ Sulaimani Construction Laboratory");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Date of order");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Date of sale listing");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Name of the recipient");

        ProductNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameFieldActionPerformed(evt);
            }
        });

        PriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceFieldActionPerformed(evt);
            }
        });

        NoteArea.setColumns(20);
        NoteArea.setRows(5);
        jScrollPane1.setViewportView(NoteArea);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons/save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        View_SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons/updateicon.png"))); // NOI18N
        View_SearchButton.setText("View\\Search");
        View_SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_SearchButtonActionPerformed(evt);
            }
        });

        update_deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons/deleteicon.png"))); // NOI18N
        update_deleteButton.setText("Update\\Delete");
        update_deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warehouse/icons/clearicon.png"))); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        PageIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PageIDFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Accounting_71_APanelLayout = new javax.swing.GroupLayout(Accounting_71_APanel);
        Accounting_71_APanel.setLayout(Accounting_71_APanelLayout);
        Accounting_71_APanelLayout.setHorizontalGroup(
            Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(MinistryLabel))
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(View_SearchButton)
                                .addGap(31, 31, 31)
                                .addComponent(update_deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PageIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(ProductNameField))
                                .addGap(108, 108, 108)
                                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Date_Of_SaleChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Date_Of_OrderChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(OfficeLabel)))
                            .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(UnitField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(108, 108, 108)
                                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Current_DateField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(RecipentField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1))))
                .addGap(48, 48, 48))
        );
        Accounting_71_APanelLayout.setVerticalGroup(
            Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(MinistryLabel)
                    .addComponent(OfficeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(PageIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)))
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_Of_OrderChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(ProductNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(Date_Of_SaleChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Current_DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RecipentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)))
                .addGap(12, 12, 12)
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Accounting_71_APanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(Accounting_71_APanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_SearchButton)
                    .addComponent(update_deleteButton)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        TabbedPane.addTab("Accounting 71 A", Accounting_71_APanel);

        importPanel.add(TabbedPane, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(importPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean collectImportData() {
        String ministry = MinistryLabel.getText().trim();
        String office = OfficeLabel.getText().trim();
        String product = ProductNameField.getText().trim();
        String quantityStr = QuantityField.getText().trim();
        String unit = UnitField.getText().trim();
        String priceStr = PriceField.getText().trim();
        Date dateOfOrder = Date_Of_OrderChooser.getDate();
        Date dateOfSale = Date_Of_SaleChooser.getDate();
        String recipient = RecipentField.getText().trim();
        String note = NoteArea.getText().trim(); // Optional field

        // Validate required fields (Note is optional)
        if (product.isEmpty() || quantityStr.isEmpty() || unit.isEmpty() || priceStr.isEmpty() ||
            dateOfOrder == null || dateOfSale == null || recipient.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields", 
                                          "Incomplete Form", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Validate numeric fields
        double quantity;
        try {
            quantity = Double.parseDouble(quantityStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Quantity must be a number", 
                                          "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        double price;
        try {
            price = Double.parseDouble(priceStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price must be a number", 
                                          "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Set values in importManager
        importManager.setMinistry(ministry);
        importManager.setOffice(office);
        importManager.setProduct(product);
        importManager.setQuantity(quantity);
        importManager.setUnit(unit);
        importManager.setPrice(price);
        importManager.setDateOfOrder(dateOfOrder);
        importManager.setDateOfSale(dateOfSale);
        importManager.setRecipient(recipient);
        importManager.setNote(note.isEmpty() ? null : note); // Null if empty

        return true;
    }
    
    private void clearFields() {
        ProductNameField.setText("");
        QuantityField.setText("");
        UnitField.setText("");
        PriceField.setText("");
        Date_Of_OrderChooser.setDate(null);
        Date_Of_SaleChooser.setDate(null);
        RecipentField.setText("");
        NoteArea.setText("");
        Current_DateField.setText(""); // Reset display field
        PageIDField.setText(""); // Reset, though not used for new entries
    }
    
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void update_deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_deleteButtonActionPerformed

        
    }//GEN-LAST:event_update_deleteButtonActionPerformed

    private void View_SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_SearchButtonActionPerformed
        JOptionPane.showMessageDialog(this, "View/Search functionality to be implemented in a new frame", 
                                      "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_View_SearchButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (collectImportData()) {
            importManager.addImport();
            clearFields();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void ProductNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameFieldActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void PageIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PageIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PageIDFieldActionPerformed

    private void PriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceFieldActionPerformed

    public void cleanup() {
        if (importManager != null) {
            importManager.closeConnection();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accounting_70Panel;
    private javax.swing.JPanel Accounting_71_APanel;
    private javax.swing.JTextField Current_DateField;
    private com.toedter.calendar.JDateChooser Date_Of_OrderChooser;
    private com.toedter.calendar.JDateChooser Date_Of_SaleChooser;
    private javax.swing.JLabel MinistryLabel;
    private javax.swing.JTextArea NoteArea;
    private javax.swing.JLabel OfficeLabel;
    private javax.swing.JTextField PageIDField;
    private javax.swing.JTextField PriceField;
    private javax.swing.JTextField ProductNameField;
    private javax.swing.JTextField QuantityField;
    private javax.swing.JTextField RecipentField;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTextField UnitField;
    private javax.swing.JButton View_SearchButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JPanel importPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton update_deleteButton;
    // End of variables declaration//GEN-END:variables
}
